import math
import struct

def float_to_hex(f):
    return hex(struct.unpack('<I', struct.pack('<f', f))[0])

def generate_c_array(name, values):
    print(f"float {name}[] = {{")
    for v in values:
        if math.isnan(v):
            print("    0.0f/0.0f, // NaN")
        elif math.isinf(v):
            if v > 0:
                print("    1.0f/0.0f, // Infinity")
            else:
                print("    -1.0f/0.0f, // -Infinity")
        else:
            s = f"{v:.9g}"
            if "." not in s and "e" not in s:
                s += ".0"
            print(f"    {s}f,")
    print("};")

def generate_tests():
    print("#ifndef MATH_TEST_VECTORS_C")
    print("#define MATH_TEST_VECTORS_C")
    print("// Generated by generate_math_tests.py")
    print("")

    # SQRT
    sqrt_inputs = [0.0, -0.0, 1.0, 4.0, 9.0, 2.0, 0.5, 100.0, 1e-5, 1e5, -1.0, -4.0, float('inf'), float('nan')]
    sqrt_expected = []
    for x in sqrt_inputs:
        try:
            sqrt_expected.append(math.sqrt(x))
        except ValueError:
            sqrt_expected.append(float('nan'))
    
    print(f"#define NUM_SQRT {len(sqrt_inputs)}")
    generate_c_array("sqrt_inputs", sqrt_inputs)
    generate_c_array("sqrt_expected", sqrt_expected)
    print("")

    # EXP
    exp_inputs = [0.0, 1.0, -1.0, 0.5, -0.5, 10.0, -10.0, 88.0, 89.0, -88.0, -89.0, float('inf'), float('-inf'), float('nan')]
    exp_expected = []
    for x in exp_inputs:
        try:
            val = math.exp(x)
            if val > 3.40282347e38: # Max float
                exp_expected.append(float('inf'))
            else:
                exp_expected.append(val)
        except OverflowError:
            exp_expected.append(float('inf'))
    
    print(f"#define NUM_EXP {len(exp_inputs)}")
    generate_c_array("exp_inputs", exp_inputs)
    generate_c_array("exp_expected", exp_expected)
    print("")

    # POW
    pow_x = [2.0, 2.0, 2.0, 0.0, 0.0, 1.0, 1.0, -2.0, -2.0, 0.5, 4.0, float('inf'), 1.0]
    pow_y = [0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 2.0, 2.0, 3.0, 2.0, 0.5, 2.0, float('inf')]
    pow_expected = []
    for x, y in zip(pow_x, pow_y):
        try:
            val = math.pow(x, y)
            if val > 3.40282347e38:
                pow_expected.append(float('inf'))
            else:
                pow_expected.append(val)
        except ValueError:
            pow_expected.append(float('nan'))
        except OverflowError:
            pow_expected.append(float('inf'))

    print(f"#define NUM_POW {len(pow_x)}")
    generate_c_array("pow_x", pow_x)
    generate_c_array("pow_y", pow_y)
    generate_c_array("pow_expected", pow_expected)
    print("")

    # TRIG (SIN/COS)
    trig_inputs = [0.0, math.pi/6, math.pi/4, math.pi/3, math.pi/2, math.pi, 2*math.pi, -math.pi/2, 10*math.pi, float('nan'), float('inf')]
    sin_expected = []
    cos_expected = []
    for x in trig_inputs:
        try:
            sin_expected.append(math.sin(x))
        except ValueError:
            sin_expected.append(float('nan'))
            
        try:
            cos_expected.append(math.cos(x))
        except ValueError:
            cos_expected.append(float('nan'))
    
    print(f"#define NUM_TRIG {len(trig_inputs)}")
    generate_c_array("sin_inputs", trig_inputs)
    generate_c_array("sin_expected", sin_expected)
    generate_c_array("cos_inputs", trig_inputs) # Same inputs
    generate_c_array("cos_expected", cos_expected)
    print("")

    # FABS
    fabs_inputs = [0.0, -0.0, 1.0, -1.0, 123.456, -123.456, float('inf'), float('-inf'), float('nan')]
    fabs_expected = []
    for x in fabs_inputs:
        fabs_expected.append(math.fabs(x))
    
    print(f"#define NUM_FABS {len(fabs_inputs)}")
    generate_c_array("fabs_inputs", fabs_inputs)
    generate_c_array("fabs_expected", fabs_expected)
    print("")

    print("#endif")

if __name__ == "__main__":
    import sys
    # Redirect stdout to the file
    original_stdout = sys.stdout
    with open("math_test_vectors.c", "w", encoding="utf-8") as f:
        sys.stdout = f
        generate_tests()
    sys.stdout = original_stdout
