#ifndef MATH_TEST_VECTORS_C
#define MATH_TEST_VECTORS_C
// Generated by generate_math_tests.py

#define NUM_SQRT 14
float sqrt_inputs[] = {
    0.0f,
    -0.0f,
    1.0f,
    4.0f,
    9.0f,
    2.0f,
    0.5f,
    100.0f,
    1e-05f,
    100000.0f,
    -1.0f,
    -4.0f,
    1.0f/0.0f, // Infinity
    0.0f/0.0f, // NaN
};
float sqrt_expected[] = {
    0.0f,
    -0.0f,
    1.0f,
    2.0f,
    3.0f,
    1.41421356f,
    0.707106781f,
    10.0f,
    0.00316227766f,
    316.227766f,
    0.0f/0.0f, // NaN
    0.0f/0.0f, // NaN
    1.0f/0.0f, // Infinity
    0.0f/0.0f, // NaN
};

#define NUM_EXP 14
float exp_inputs[] = {
    0.0f,
    1.0f,
    -1.0f,
    0.5f,
    -0.5f,
    10.0f,
    -10.0f,
    88.0f,
    89.0f,
    -88.0f,
    -89.0f,
    1.0f/0.0f, // Infinity
    -1.0f/0.0f, // -Infinity
    0.0f/0.0f, // NaN
};
float exp_expected[] = {
    1.0f,
    2.71828183f,
    0.367879441f,
    1.64872127f,
    0.60653066f,
    22026.4658f,
    4.53999298e-05f,
    1.65163625e+38f,
    1.0f/0.0f, // Infinity
    6.0546019e-39f,
    2.22736356e-39f,
    1.0f/0.0f, // Infinity
    0.0f,
    0.0f/0.0f, // NaN
};

#define NUM_POW 13
float pow_x[] = {
    2.0f,
    2.0f,
    2.0f,
    0.0f,
    0.0f,
    1.0f,
    1.0f,
    -2.0f,
    -2.0f,
    0.5f,
    4.0f,
    1.0f/0.0f, // Infinity
    1.0f,
};
float pow_y[] = {
    0.0f,
    1.0f,
    2.0f,
    0.0f,
    1.0f,
    0.0f,
    2.0f,
    2.0f,
    3.0f,
    2.0f,
    0.5f,
    2.0f,
    1.0f/0.0f, // Infinity
};
float pow_expected[] = {
    1.0f,
    2.0f,
    4.0f,
    1.0f,
    0.0f,
    1.0f,
    1.0f,
    4.0f,
    -8.0f,
    0.25f,
    2.0f,
    1.0f/0.0f, // Infinity
    1.0f,
};

#define NUM_TRIG 11
float sin_inputs[] = {
    0.0f,
    0.523598776f,
    0.785398163f,
    1.04719755f,
    1.57079633f,
    3.14159265f,
    6.28318531f,
    -1.57079633f,
    31.4159265f,
    0.0f/0.0f, // NaN
    1.0f/0.0f, // Infinity
};
float sin_expected[] = {
    0.0f,
    0.5f,
    0.707106781f,
    0.866025404f,
    1.0f,
    1.2246468e-16f,
    -2.4492936e-16f,
    -1.0f,
    -1.2246468e-15f,
    0.0f/0.0f, // NaN
    0.0f/0.0f, // NaN
};
float cos_inputs[] = {
    0.0f,
    0.523598776f,
    0.785398163f,
    1.04719755f,
    1.57079633f,
    3.14159265f,
    6.28318531f,
    -1.57079633f,
    31.4159265f,
    0.0f/0.0f, // NaN
    1.0f/0.0f, // Infinity
};
float cos_expected[] = {
    1.0f,
    0.866025404f,
    0.707106781f,
    0.5f,
    6.123234e-17f,
    -1.0f,
    1.0f,
    6.123234e-17f,
    1.0f,
    0.0f/0.0f, // NaN
    0.0f/0.0f, // NaN
};

#define NUM_FABS 9
float fabs_inputs[] = {
    0.0f,
    -0.0f,
    1.0f,
    -1.0f,
    123.456f,
    -123.456f,
    1.0f/0.0f, // Infinity
    -1.0f/0.0f, // -Infinity
    0.0f/0.0f, // NaN
};
float fabs_expected[] = {
    0.0f,
    0.0f,
    1.0f,
    1.0f,
    123.456f,
    123.456f,
    1.0f/0.0f, // Infinity
    1.0f/0.0f, // Infinity
    0.0f/0.0f, // NaN
};

#endif
